name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-clang
    
    - name: Download Vulkan SDK
      shell: powershell
      run: |
        $vulkanSdkUrl = "https://sdk.lunarg.com/sdk/download/1.3.268.0/windows/VulkanSDK-1.3.268.0-Installer.exe"
        Invoke-WebRequest -Uri $vulkanSdkUrl -OutFile VulkanSDK-Installer.exe
        Start-Process -FilePath .\VulkanSDK-Installer.exe -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
    
    - name: Set Vulkan SDK Environment Variable
      shell: msys2 {0}
      run: |
        echo "VULKAN_SDK=C:/VulkanSDK/1.3.268.0" >> $GITHUB_ENV
    
    - name: Build Project (Release Mode)
      run: |
        make release
    
    - name: Create ZIP Archive
      shell: powershell
      run: |
        Compress-Archive -Path release\* -DestinationPath forest-game.zip
    
    - name: Extract Version from Tag
      id: get_version
      shell: bash
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3 | cut -d- -f1)
        echo "MAJOR=$MAJOR" >> $GITHUB_OUTPUT
        echo "MINOR=$MINOR" >> $GITHUB_OUTPUT
        echo "PATCH=$PATCH" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Forest Game v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Changelog
          - no changes yet
        files: |
          forest.zip
        draft: false
        prerelease: true
        generate_release_notes: true